"""Shared FastAPI dependencies: auth, roles, guest session, kitchen key, order access."""
import re
import secrets

from fastapi import Depends, Header, HTTPException, status
from fastapi.security import HTTPAuthorizationCredentials, HTTPBearer

from app.core.config import settings
from app.core.database import get_db
from app.core.security import decode_token, hash_token

bearer = HTTPBearer(auto_error=False)
_SESSION_RE = re.compile(r"^[A-Za-z0-9_\-]{8,100}$")


async def get_current_user_optional(creds: HTTPAuthorizationCredentials | None = Depends(bearer), db=Depends(get_db)):
    if not creds:
        return None
    payload = decode_token(creds.credentials, "access")
    user = await db.users.find_one({"_id": payload["sub"], "is_deleted": {"$ne": True}})
    if not user or not user.get("is_active", True):
        raise HTTPException(status.HTTP_401_UNAUTHORIZED, "User not found or disabled")
    return user


async def get_current_user(user=Depends(get_current_user_optional)):
    if not user:
        raise HTTPException(status.HTTP_401_UNAUTHORIZED, "Not authenticated",
                            headers={"WWW-Authenticate": "Bearer"})
    return user


def require_roles(*roles: str):
    async def dependency(user=Depends(get_current_user)):
        if user["role"] not in roles:
            raise HTTPException(status.HTTP_403_FORBIDDEN, "You don't have permission to do this")
        return user
    return dependency


require_staff = require_roles("staff", "admin")
require_admin = require_roles("admin")


async def get_session_id(x_session_id: str | None = Header(None, description="Guest cart id (random, generated by the frontend)")):
    if x_session_id is None:
        return None
    if not _SESSION_RE.match(x_session_id):
        raise HTTPException(400, "X-Session-Id must be 8-100 characters: letters, numbers, - or _")
    return x_session_id


async def verify_kitchen_key(x_kitchen_key: str = Header(..., description="Robot kitchen API key")):
    if not secrets.compare_digest(x_kitchen_key, settings.KITCHEN_API_KEY):
        raise HTTPException(status.HTTP_401_UNAUTHORIZED, "Invalid kitchen key")
    return True


def can_view_order(order: dict, user: dict | None, order_token: str | None) -> bool:
    if user and (user["role"] in ("staff", "admin") or order.get("user_id") == user["_id"]):
        return True
    return bool(order_token) and secrets.compare_digest(hash_token(order_token), order.get("access_token_hash", ""))


async def get_order_for_viewer(
    order_id: str,
    x_order_token: str | None = Header(None, description="Guest order access token returned by checkout"),
    user=Depends(get_current_user_optional),
    db=Depends(get_db),
):
    order = await db.orders.find_one({"_id": order_id})
    if not order or not can_view_order(order, user, x_order_token):
        raise HTTPException(404, "Order not found")
    return order
